# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/14683/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/d_mem/d_mem.xci
# IP: The module: 'd_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14683/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/d_mem/d_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/14683/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/d_mem/d_mem.xci
# IP: The module: 'd_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14683/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/d_mem/d_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'd_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
