# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/Mem_1/Mem.xci
# IP: The module: 'Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/Mem_1/Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/Mem_1/Mem.xci
# IP: The module: 'Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Documents/GitHub/convplex/convplex.srcs/sources_1/ip/Mem_1/Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
